spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG

app:
  upload:
    file-path: src/main/resources/images
    extensions: pdf, doc, docx, xls, xlsx, ppt, pptx, jpg, jpeg, png, gif, bmp, zip, rar, txt, csv